export type RegionalSetEntry = { code: string; name: string; era: string };

export const JAPANESE_SET_CATALOG: RegionalSetEntry[] = [
  { code: "M6", name: "Storm Emeralda", era: "Mega Evolution" },
  { code: "M5", name: "Abyss Eye", era: "Mega Evolution" },
  { code: "M4", name: "Ninja Spinner", era: "Mega Evolution" },
  { code: "M3", name: "Nihil Zero", era: "Mega Evolution" },
  { code: "M2A", name: "MEGA Dream ex", era: "Mega Evolution" },
  { code: "M2", name: "Inferno X", era: "Mega Evolution" },
  { code: "M1S", name: "Mega Symphonia", era: "Mega Evolution" },
  { code: "M1L", name: "Mega Brave", era: "Mega Evolution" },
  { code: "SV11W", name: "White Flare", era: "Scarlet & Violet" },
  { code: "SV11B", name: "Black Bolt", era: "Scarlet & Violet" },
  { code: "SV10", name: "Glory of the Team Rocket", era: "Scarlet & Violet" },
  { code: "SV9A", name: "Heat Wave Arena", era: "Scarlet & Violet" },
  { code: "SV9", name: "Battle Partners", era: "Scarlet & Violet" },
  { code: "SV8A", name: "Terastal Fest ex", era: "Scarlet & Violet" },
  { code: "SV8", name: "Super Electric Breaker", era: "Scarlet & Violet" },
  { code: "SV7A", name: "Paradise Dragona", era: "Scarlet & Violet" },
  { code: "SV7", name: "Stellar Miracle", era: "Scarlet & Violet" },
  { code: "SV6A", name: "Night Wanderer", era: "Scarlet & Violet" },
  { code: "SV6", name: "Mask of Change", era: "Scarlet & Violet" },
  { code: "SV5A", name: "Crimson Haze", era: "Scarlet & Violet" },
  { code: "SV5M", name: "Cyber Judge", era: "Scarlet & Violet" },
  { code: "SV5K", name: "Wild Force", era: "Scarlet & Violet" },
  { code: "SV4A", name: "Shiny Treasure ex", era: "Scarlet & Violet" },
  { code: "SV3A", name: "Raging Surf", era: "Scarlet & Violet" },
  { code: "SV3", name: "Ruler of the Black Flame", era: "Scarlet & Violet" },
  { code: "SV2A", name: "Pokémon Card 151", era: "Scarlet & Violet" },
  { code: "SV2D", name: "Clay Burst", era: "Scarlet & Violet" },
  { code: "SV2P", name: "Snow Hazard", era: "Scarlet & Violet" },
  { code: "SV1A", name: "Triplet Beat", era: "Scarlet & Violet" },
  { code: "SV1V", name: "Violet ex", era: "Scarlet & Violet" },
  { code: "SV1S", name: "Scarlet ex", era: "Scarlet & Violet" },
];

export const CHINESE_SET_CATALOG: RegionalSetEntry[] = [
  { code: "CBB6C", name: "Gem Pack Vol. 6", era: "Simplified Chinese" },
  { code: "CSV10C", name: "Chasing Glory Together", era: "Scarlet & Violet" },
  { code: "CSV9.5C", name: "Grand Terastal Gathering", era: "Simplified Chinese" },
  { code: "CSV9C", name: "Stellar Crystal", era: "Scarlet & Violet" },
  { code: "CBB5C", name: "Gem Pack Volume 5", era: "Scarlet & Violet" },
  { code: "CSV8C", name: "Brilliant Fantasy", era: "Scarlet & Violet" },
  { code: "CBB4C", name: "Gem Pack Volume 4", era: "Scarlet & Violet" },
  { code: "CSV7C", name: "Blade Awakenings", era: "Scarlet & Violet" },
  { code: "CSVL2C", name: "Travel Special Pack", era: "Scarlet & Violet" },
  { code: "CSV6C", name: "Arcane Truth", era: "Scarlet & Violet" },
  { code: "CBB3C", name: "Gem Pack Volume 3", era: "Scarlet & Violet" },
  { code: "CSV5C", name: "Dark Crystal Blaze", era: "Scarlet & Violet" },
  { code: "CSV4C", name: "Bonus Round", era: "Scarlet & Violet" },
  { code: "CSVL1C", name: "Departure Special Pack", era: "Scarlet & Violet" },
  { code: "CBB2C", name: "Gem Pack Volume 2", era: "Scarlet & Violet" },
  { code: "CSV3C", name: "Fearless Terastal", era: "Scarlet & Violet" },
  { code: "CSV2C", name: "Miracle Journey", era: "Scarlet & Violet" },
  { code: "CBB1C", name: "Gem Pack Volume 1", era: "Scarlet & Violet" },
  { code: "151C", name: "Collect 151", era: "Scarlet & Violet" },
  { code: "CSV1C", name: "Eternal Birth", era: "Scarlet & Violet" },
  { code: "CS65C", name: "Victory Star Guide", era: "Sword & Shield" },
  { code: "CS6BC", name: "Azure Shadow - Pursuit", era: "Sword & Shield" },
  { code: "CS6AC", name: "Azure Shadow - Roar", era: "Sword & Shield" },
  { code: "CS55C", name: "Shadow of Glory", era: "Sword & Shield" },
  { code: "CS5BC", name: "Brave Stars - Brave", era: "Sword & Shield" },
  { code: "CS5AC", name: "Brave Stars - Charm", era: "Sword & Shield" },
  { code: "CS4BC", name: "Nine Colors Gathering - Origin", era: "Sword & Shield" },
  { code: "CS4AC", name: "Nine Colors Gathering - Friends", era: "Sword & Shield" },
  { code: "CS3BC", name: "Primordial Arts Torrent", era: "Sword & Shield" },
  { code: "CS3AC", name: "Primordial Arts Overgrow", era: "Sword & Shield" },
  { code: "CS2BC", name: "Vivid Portrayals Indigo", era: "Sword & Shield" },
  { code: "CS2AC", name: "Vivid Portrayals Obsidian", era: "Sword & Shield" },
  { code: "CS1BC", name: "Dynamax Clash Flame", era: "Sword & Shield" },
  { code: "CS1AC", name: "Dynamax Clash Thunder", era: "Sword & Shield" },
  { code: "CSM2CC", name: "Shining Synergy Summon", era: "Sun & Moon" },
  { code: "CSM2BC", name: "Shining Synergy Supreme", era: "Sun & Moon" },
  { code: "CSM2AC", name: "Shining Synergy Shower", era: "Sun & Moon" },
  { code: "CSM1CC", name: "Storming Emergence Abundant", era: "Sun & Moon" },
  { code: "CSM1BC", name: "Storming Emergence Verdant", era: "Sun & Moon" },
  { code: "CSM1AC", name: "Storming Emergence Radiant", era: "Sun & Moon" },
  { code: "30THP", name: "30th Anniversary Celebration", era: "Promos" },
  { code: "NRGY", name: "Energies", era: "Promos" },
];
