import { NextResponse } from "next/server";
import type { MarketConfidence, MarketQuote, MarketSyncStatus } from "@/lib/types";

type CardLanguage = "fr" | "en" | "ja" | "zh-tw";
type InputCard = { id:string; name?:string; number?:string; setId?:string; setName?:string; variant?:string; rarity?:string; language?:CardLanguage };
type MarketPayload = {
  cardmarket?: { prices?: Record<string, number>; url?: string; updatedAt?: string };
  tcgplayer?: { prices?: Record<string, any>; url?: string; updatedAt?: string; currency?: "EUR" };
  justtcg?: { medianNearMint?: number; language?: string; printing?: string; sampleSize?: number; url?: string; updatedAt?: string };
  ebayListings?: { median?: number; sampleSize?: number; url?: string; updatedAt?: string };
  quotes: MarketQuote[];
  estimate?: { price:number; language:CardLanguage; currency:"EUR"; condition:"Near Mint"; confidence:MarketConfidence; includedSources:string[]; excludedSources:Array<{source:string;reason:string}> };
  status: MarketSyncStatus;
  sources: { cardmarket:boolean; tcgplayer:boolean; justtcg:boolean; ebayListings:boolean; tcggo?:boolean };
};

type FetchResult={data:any|null;status:"ok"|"not_found"|"rate_limited"|"unavailable"};
const TCGDEX="https://api.tcgdex.net/v2";
const POKEMON="https://api.pokemontcg.io/v2";
const JUSTTCG="https://api.justtcg.com/v1";
const TCGGO_HOST=process.env.TCGGO_API_HOST||"pokemon-tcg-api.p.rapidapi.com";
const RATE_FALLBACK=0.92;
const cache=new Map<string,{expires:number;value:MarketPayload}>();
let fx:{value:number;expires:number}|null=null;

const num=(v:unknown):number|undefined=>{const n=Number(v);return Number.isFinite(n)&&n>0?Number(n.toFixed(2)):undefined};
const cleanNumber=(v?:string)=>String(v||"").trim().split("/")[0].trim();
const normNumber=(v?:string)=>{const raw=cleanNumber(v).toUpperCase();const p=raw.match(/^[A-Z]+/)?.[0]||"";const d=raw.replace(/^[A-Z]+/,"").replace(/^0+(?=\d)/,"");return `${p}${d||"0"}`};
const norm=(v?:string)=>String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\u3040-\u30ff\u3400-\u9fff]/g,"");
const normSet=(v?:string)=>String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"");
const median=(a:number[])=>{const s=[...a].sort((x,y)=>x-y);if(!s.length)return 0;const m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};

async function json(url:string,init?:RequestInit):Promise<FetchResult>{const c=new AbortController();const timer=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{...init,cache:"no-store",signal:c.signal,headers:{Accept:"application/json",...(init?.headers||{})}});if(r.status===429)return{data:null,status:"rate_limited"};if(r.status===404)return{data:null,status:"not_found"};if(!r.ok)return{data:null,status:"unavailable"};return{data:await r.json(),status:"ok"}}catch{return{data:null,status:"unavailable"}}finally{clearTimeout(timer)}}
async function eur(){if(fx&&fx.expires>Date.now())return fx.value;const r=await json("https://api.frankfurter.app/latest?from=USD&to=EUR");const n=Number(r.data?.rates?.EUR);const value=Number.isFinite(n)&&n>0?n:RATE_FALLBACK;fx={value,expires:Date.now()+43200000};return value}
function empty(status:MarketSyncStatus="not_listed"):MarketPayload{return{quotes:[],status,sources:{cardmarket:false,tcgplayer:false,justtcg:false,ebayListings:false,tcggo:false}}}
function addQuote(payload:MarketPayload,quote:MarketQuote){if(!payload.quotes.some(q=>q.source===quote.source&&q.language===quote.language&&q.metric===quote.metric))payload.quotes.push(quote)}
function identity(detail:any,card:InputCard){if(normNumber(detail?.localId??detail?.number)!==normNumber(card.number))return false;const wanted=normSet(card.setId);if(!wanted)return true;const actual=normSet(detail?.set?.id)||normSet(String(detail?.id||"").split("-")[0]);return actual===wanted}
function ids(card:InputCard){const out=new Set<string>();const wrapped=String(card.id||"").match(/^tcgdex-(?:fr|en|ja|zh-tw|zh-cn)-(.+)$/i)?.[1];if(wrapped)out.add(wrapped);if(card.setId&&card.number)out.add(`${String(card.setId).toLowerCase()}-${cleanNumber(card.number)}`);return [...out]}
function locales(lang?:CardLanguage){if(lang==="ja")return["ja"];if(lang==="zh-tw")return["zh-tw"];if(lang==="fr")return["fr"];return["en"]}

async function tcgdex(card:InputCard):Promise<MarketPayload>{const p=empty();const rate=await eur();for(const locale of locales(card.language)){for(const id of ids(card)){const r=await json(`${TCGDEX}/${locale}/cards/${encodeURIComponent(id)}`);if(!r.data?.id||!identity(r.data,card))continue;const cm=r.data?.pricing?.cardmarket;const tcg=r.data?.pricing?.tcgplayer;
      // TCGdex Cardmarket est une valeur générique, jamais une preuve de prix FR.
      if(cm){const low=num(cm.low);const trend=num(cm.trend);const avg=num(cm.avg);p.cardmarket={prices:{...(low?{lowPrice:low}:{}),...(trend?{trendPrice:trend}:{}),...(avg?{averageSellPrice:avg}:{})},updatedAt:cm.updated};const display=low||trend||avg;if(display)addQuote(p,{source:"cardmarket",label:"Cardmarket Europe (générique)",price:display,currency:"EUR",language:"multi",condition:"Near Mint",metric:low?"lowest_listing":"market",compatible:card.language==="en",confidence:"limited",updatedAt:cm.updated})}
      if(tcg&&card.language==="en"){const prices:Record<string,any>={};for(const [key,v] of Object.entries(tcg)){if(!v||typeof v!=="object")continue;const market=num((v as any).marketPrice);const low=num((v as any).lowPrice);if(market||low)prices[key]={...(market?{market:Number((market*rate).toFixed(2))}:{}),...(low?{low:Number((low*rate).toFixed(2))}:{})}}if(Object.keys(prices).length){p.tcgplayer={prices,currency:"EUR",updatedAt:tcg.updated};const vals=Object.values(prices).map((v:any)=>num(v.market??v.low)).filter((v: number | undefined): v is number => v !== undefined);if(vals.length)addQuote(p,{source:"tcgplayer",label:"TCGPlayer Market (EN)",price:Number(median(vals).toFixed(2)),currency:"EUR",language:"en",condition:"Near Mint",metric:"market",compatible:true,confidence:"medium",updatedAt:tcg.updated})}}
      return p}}
  return p}

async function pokemon(card:InputCard):Promise<MarketPayload>{if(card.language!=="en"||!card.id||card.id.startsWith("tcgdex-"))return empty();const key=process.env.POKEMON_TCG_API_KEY;const r=await json(`${POKEMON}/cards/${encodeURIComponent(card.id)}`,{headers:key?{"X-Api-Key":key}:{}});if(!r.data?.data)return empty(r.status==="rate_limited"?"rate_limited":"not_listed");const d=r.data.data;const rate=await eur();const p=empty();const cm=d.cardmarket;const tcg=d.tcgplayer;if(cm?.prices){p.cardmarket=cm;const value=num(cm.prices.lowPrice??cm.prices.trendPrice??cm.prices.averageSellPrice);if(value)addQuote(p,{source:"cardmarket",label:"Cardmarket Europe (EN)",price:value,currency:"EUR",language:"en",condition:"Near Mint",metric:"lowest_listing",compatible:true,confidence:"medium",url:cm.url,updatedAt:cm.updatedAt})}if(tcg?.prices){const prices:Record<string,any>={};for(const [k,v] of Object.entries(tcg.prices)){const market=num((v as any)?.market);const low=num((v as any)?.low);if(market||low)prices[k]={...(market?{market:Number((market*rate).toFixed(2))}:{}),...(low?{low:Number((low*rate).toFixed(2))}:{})}}if(Object.keys(prices).length){p.tcgplayer={prices,currency:"EUR",url:tcg.url,updatedAt:tcg.updatedAt};const vals=Object.values(prices).map((v:any)=>num(v.market??v.low)).filter((v: number | undefined): v is number => v !== undefined);if(vals.length)addQuote(p,{source:"tcgplayer",label:"TCGPlayer Market (EN)",price:Number(median(vals).toFixed(2)),currency:"EUR",language:"en",condition:"Near Mint",metric:"market",compatible:true,confidence:"high",url:tcg.url,updatedAt:tcg.updatedAt})}}return p}

async function justtcg(card:InputCard):Promise<MarketPayload>{const key=process.env.JUSTTCG_API_KEY;if(!key||!card.name)return empty();const game=card.language==="ja"?"pokemon-japan":"pokemon";const params=new URLSearchParams({q:card.name,game,limit:"20"});if(card.number)params.set("number",cleanNumber(card.number));const r=await json(`${JUSTTCG}/cards?${params}`,{headers:{"x-api-key":key}});if(!r.data)return empty(r.status==="rate_limited"?"rate_limited":"not_listed");const list=Array.isArray(r.data?.data)?r.data.data:[];const item=list.find((x:any)=>norm(x.name)===norm(card.name)&&normNumber(x.number)===normNumber(card.number)&&(!card.setName||norm(x.set_name??x.set?.name).includes(norm(card.setName))||norm(card.setName).includes(norm(x.set_name??x.set?.name))));if(!item)return empty();const expected=card.language==="ja"?"japanese":card.language==="zh-tw"?"chinese":card.language==="fr"?"french":"english";const variants=(Array.isArray(item.variants)?item.variants:[]).filter((v:any)=>String(v.condition||"").toLowerCase()==="near mint"&&String(v.language||"").toLowerCase().includes(expected)&&num(v.price)!==undefined);if(!variants.length)return empty();const rate=await eur();const values=variants.map((v:any)=>num(v.price)).filter((v:number|undefined):v is number=>v!==undefined).map((v: number) => Number((v * rate).toFixed(2)));const value=Number(median(values).toFixed(2));const p=empty();p.justtcg={medianNearMint:value,language:expected,printing:String(variants[0]?.printing||""),sampleSize:variants.length,url:item.url,updatedAt:item.updatedAt};addQuote(p,{source:"justtcg",label:`JustTCG médiane NM (${expected})`,price:value,currency:"EUR",language:card.language||"en",condition:"Near Mint",metric:"median",compatible:true,confidence:variants.length>=3?"medium":"limited",url:item.url,sampleSize:variants.length});return p}

async function tcggo(card:InputCard):Promise<MarketPayload>{const key=process.env.TCGGO_API_KEY||process.env.RAPIDAPI_KEY;if(!key||!card.name)return empty();const query=`${card.name} ${cleanNumber(card.number)} ${card.setName||""}`.trim();const r=await json(`https://${TCGGO_HOST}/cards?search=${encodeURIComponent(query)}&limit=20`,{headers:{"x-rapidapi-key":key,"x-rapidapi-host":TCGGO_HOST}});if(!r.data)return empty(r.status==="rate_limited"?"rate_limited":"not_listed");const list=Array.isArray(r.data)?r.data:Array.isArray(r.data?.data)?r.data.data:Array.isArray(r.data?.results)?r.data.results:[];const item=list.find((x:any)=>normNumber(x.card_number??x.number)===normNumber(card.number)&&(!card.setName||norm(x.episode?.name??x.set_name??x.set?.name).includes(norm(card.setName))||norm(card.setName).includes(norm(x.episode?.name??x.set_name??x.set?.name))));if(!item)return empty();const cm=item.prices?.cardmarket||{};const field=card.language==="fr"?cm.lowest_near_mint_FR:card.language==="en"?cm.lowest_near_mint:undefined;const p=empty();const value=num(field);if(value){p.cardmarket={prices:{lowPrice:value},url:item.tcggo_url};addQuote(p,{source:"tcggo",label:card.language==="fr"?"Cardmarket FR · 1re offre NM":"Cardmarket EN · 1re offre NM",price:value,currency:"EUR",language:card.language||"en",condition:"Near Mint",metric:"lowest_listing",compatible:true,confidence:"high",url:item.tcggo_url})}const ebay=num(item.prices?.ebay?.raw?.median_price??item.prices?.ebay?.ungraded?.median_price);if(ebay){const rate=await eur();const ev=Number((ebay*rate).toFixed(2));p.ebayListings={median:ev,sampleSize:item.prices?.ebay?.raw?.sample_size,url:item.tcggo_url};addQuote(p,{source:"ebay",label:"eBay ventes RAW médiane",price:ev,currency:"EUR",language:card.language||"multi",condition:"Near Mint",metric:"sold_median",compatible:true,confidence:"medium",url:item.tcggo_url,sampleSize:item.prices?.ebay?.raw?.sample_size})}p.sources.tcggo=Boolean(value||ebay);return p}

function merge(...parts:MarketPayload[]):MarketPayload{const p=empty();for(const x of parts){if(x.cardmarket&&!p.cardmarket)p.cardmarket=x.cardmarket;if(x.tcgplayer&&!p.tcgplayer)p.tcgplayer=x.tcgplayer;if(x.justtcg&&!p.justtcg)p.justtcg=x.justtcg;if(x.ebayListings&&!p.ebayListings)p.ebayListings=x.ebayListings;for(const q of x.quotes)addQuote(p,q);if(x.status==="rate_limited")p.status="rate_limited";if(x.status==="source_unavailable"&&p.status==="not_listed")p.status="source_unavailable";p.sources={cardmarket:Boolean(p.cardmarket),tcgplayer:Boolean(p.tcgplayer),justtcg:Boolean(p.justtcg),ebayListings:Boolean(p.ebayListings),tcggo:Boolean(p.sources.tcggo||x.sources.tcggo)}}if(p.quotes.length)p.status="available";return p}
function estimate(p:MarketPayload,lang:CardLanguage){const compatible=p.quotes.filter(q=>q.compatible&&q.language===lang&&q.price>0);const excluded=p.quotes.filter(q=>!compatible.includes(q)).map(q=>({source:q.label,reason:q.language!==lang?`Langue ${q.language} différente de ${lang}`:"Source non compatible"}));if(!compatible.length)return undefined;const values=compatible.map(q=>q.price);const med=median(values);const filtered=values.length>=3?compatible.filter(q=>q.price>=med*.25&&q.price<=med*4):compatible;const price=Number(median(filtered.map(q=>q.price)).toFixed(2));return{price,language:lang,currency:"EUR" as const,condition:"Near Mint" as const,confidence:(filtered.some(q=>q.confidence==="high")?"high":filtered.length>=2?"medium":"limited") as MarketConfidence,includedSources:filtered.map(q=>q.label),excludedSources:excluded}}

async function parallel<T,R>(items:T[],limit:number,work:(item:T)=>Promise<R>){const out=new Array<R>(items.length);let i=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(i<items.length){const n=i++;out[n]=await work(items[n])}}));return out}
export async function POST(req:Request){try{const body=await req.json();const cards=(Array.isArray(body?.cards)?body.cards:[]).filter((x:any)=>x?.id).slice(0,20) as InputCard[];const results=await parallel(cards,3,async card=>{const key=`price-v20:${card.id}:${card.language}:${card.setId}:${normNumber(card.number)}`;const hit=cache.get(key);if(hit&&hit.expires>Date.now())return[card.id,hit.value] as const;const parts=await Promise.all([tcggo(card),tcgdex(card),pokemon(card),justtcg(card)]);const value=merge(...parts);value.estimate=estimate(value,card.language||"en");cache.set(key,{expires:Date.now()+(value.status==="available"?21600000:600000),value});return[card.id,value] as const});return NextResponse.json({success:true,version:"price-engine-v20-language-exact",prices:Object.fromEntries(results)})}catch(error){console.error("[prices]",error);return NextResponse.json({success:false,error:"Impossible de récupérer les prix marché."},{status:500})}}
